# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 556adfd276f015bcc4baa932b243de2939df4a88b503c4fbccf4cf14543af152d1045dec47b287c986dd1eae08e744de676228dbb79a7e40d7598e005de5ddef

test:
  secret_key_base: 12d54d8a05b08d59a2fb51a8f5a9b13ee90a67963e8b20063ae3bc6a5ac9d515dc148aa9558c97c023be02f316da2a07338f348e041f16eaf1214a70e15e444a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
